"""
Seed dataset: 24 realistic but entirely FICTIONAL King County resources.

Names, org details, addresses, phone numbers, and websites here are invented
for demo purposes and do not represent real organizations. Street/neighborhood
names are real King County locations (used for geographic plausibility only);
building numbers, org names, and contact details are fabricated.

Distribution across the 7 PRD categories:
housing(4), food(4), healthcare(3), employment(3), childcare(3),
financial_assistance(4), legal(3) = 24 total.
"""

from datetime import date

SEED_RESOURCES = [
    # ---- Housing ----
    {
        "name": "Cedar Valley Housing Center",
        "category": "housing",
        "description": (
            "Emergency shelter and transitional housing for individuals and "
            "families experiencing homelessness. On-site case management "
            "helps residents move toward permanent housing."
        ),
        "eligibility_notes": "Priority given to families with children and King County residents.",
        "service_area": "Kent, Auburn, and South King County",
        "address": "1420 Central Ave S, Kent, WA 98032",
        "phone": "253-555-0142",
        "website": "https://cedarvalleyhousing.example.org",
        "hours": "Intake: Mon-Fri 9am-4pm; shelter open 24/7",
        "application_process": "Walk in during intake hours or call ahead for same-day availability.",
        "active": True,
        "last_verified": date(2026, 6, 15),
    },
    {
        "name": "Rainier Family Housing Assistance",
        "category": "housing",
        "description": (
            "Rental assistance and eviction prevention program providing "
            "short-term financial help plus negotiation support with landlords."
        ),
        "eligibility_notes": "Household income at or below 50% area median income; must have an active lease.",
        "service_area": "Seattle (South Seattle focus)",
        "address": "3210 Rainier Ave S, Seattle, WA 98144",
        "phone": "206-555-0198",
        "website": "https://rainierfamilyhousing.example.org",
        "hours": "Mon-Thu 10am-5pm",
        "application_process": "Online application; funds are limited and distributed on a rolling basis.",
        "active": True,
        "last_verified": date(2026, 5, 28),
    },
    {
        "name": "Lake City Emergency Shelter",
        "category": "housing",
        "description": "Overnight emergency shelter for single adults, with meals and basic hygiene services.",
        "eligibility_notes": "Adults 18+. No referral needed.",
        "service_area": "North Seattle",
        "address": "12500 Lake City Way NE, Seattle, WA 98125",
        "phone": "206-555-0134",
        "website": "https://lakecityshelter.example.org",
        "hours": "Check-in nightly 6pm-8pm; departure by 7am",
        "application_process": "Walk-in only, first come first served.",
        "active": True,
        "last_verified": date(2026, 6, 1),
    },
    {
        "name": "Skyway Housing Stability Program",
        "category": "housing",
        "description": (
            "Rapid rehousing program combining short-term rental subsidies "
            "with ongoing case management for households exiting homelessness."
        ),
        "eligibility_notes": "Must be currently unhoused or in unstable housing; referral from a partner agency preferred but not required.",
        "service_area": "Skyway, Renton, and unincorporated South King County",
        "address": "7605 S 124th St, Seattle, WA 98178",
        "phone": "206-555-0177",
        "website": "https://skywayhousingstability.example.org",
        "hours": "Mon-Fri 9am-5pm",
        "application_process": "Call to schedule an intake appointment.",
        "active": True,
        "last_verified": date(2026, 4, 20),
    },
    # ---- Food ----
    {
        "name": "Duwamish Valley Food Bank",
        "category": "food",
        "description": "Weekly grocery distribution including fresh produce, shelf-stable food, and household staples.",
        "eligibility_notes": "No income documentation required; self-declaration of need is sufficient.",
        "service_area": "South Park and Georgetown, Seattle",
        "address": "8720 14th Ave S, Seattle, WA 98108",
        "phone": "206-555-0211",
        "website": "https://duwamishvalleyfoodbank.example.org",
        "hours": "Tue and Sat 10am-2pm",
        "application_process": "No appointment needed; bring a bag or box for groceries.",
        "active": True,
        "last_verified": date(2026, 6, 20),
    },
    {
        "name": "Eastside Community Food Pantry",
        "category": "food",
        "description": "Food pantry offering a client-choice grocery model, plus a weekend backpack program for school-age children.",
        "eligibility_notes": "Open to all Eastside residents; no documentation required.",
        "service_area": "Bellevue, Redmond, Kirkland",
        "address": "1550 140th Ave NE, Bellevue, WA 98005",
        "phone": "425-555-0165",
        "website": "https://eastsidefoodpantry.example.org",
        "hours": "Wed 12pm-6pm, Fri 10am-1pm",
        "application_process": "Register at first visit; no appointment necessary for later visits.",
        "active": True,
        "last_verified": date(2026, 5, 10),
    },
    {
        "name": "Highline Mobile Food Market",
        "category": "food",
        "description": "A mobile food market truck that rotates through South King County neighborhoods weekly, distributing fresh produce and pantry staples.",
        "eligibility_notes": "Open to anyone; no ID or documentation required.",
        "service_area": "Burien, Des Moines, SeaTac",
        "address": "Rotating locations - see website for weekly schedule",
        "phone": "206-555-0188",
        "website": "https://highlinemobilemarket.example.org",
        "hours": "Varies by location; typically Thu-Sat",
        "application_process": "No application; show up at the scheduled stop.",
        "active": True,
        "last_verified": date(2026, 6, 5),
    },
    {
        "name": "Green River Meal Program",
        "category": "food",
        "description": "Hot, ready-to-eat meal service for individuals and families, served on-site or available for takeout.",
        "eligibility_notes": "Open to the public; families with children encouraged to attend.",
        "service_area": "Kent and Auburn",
        "address": "615 W Meeker St, Kent, WA 98032",
        "phone": "253-555-0119",
        "website": "https://greenrivermeals.example.org",
        "hours": "Daily 5pm-7pm",
        "application_process": "Walk in, no registration required.",
        "active": True,
        "last_verified": date(2026, 3, 30),
    },
    # ---- Healthcare ----
    {
        "name": "Sound Community Health Clinic",
        "category": "healthcare",
        "description": "Sliding-scale primary care clinic offering general medical visits, basic dental screening, and referrals to specialists.",
        "eligibility_notes": "Sliding fee scale based on income; uninsured and underinsured patients accepted.",
        "service_area": "Seattle citywide",
        "address": "2100 24th Ave S, Seattle, WA 98144",
        "phone": "206-555-0220",
        "website": "https://soundcommunityhealth.example.org",
        "hours": "Mon-Fri 8am-6pm",
        "application_process": "Call to schedule a new-patient intake appointment.",
        "active": True,
        "last_verified": date(2026, 6, 12),
    },
    {
        "name": "Valley Free Medical Clinic",
        "category": "healthcare",
        "description": "Free clinic staffed by volunteer providers, offering urgent care for minor illness/injury and basic chronic disease management.",
        "eligibility_notes": "Uninsured adults; no immigration status questions asked.",
        "service_area": "Auburn and Kent",
        "address": "402 Auburn Way S, Auburn, WA 98002",
        "phone": "253-555-0155",
        "website": "https://valleyfreemedical.example.org",
        "hours": "Tue and Thu 6pm-9pm",
        "application_process": "Walk-in clinic; arrive early as slots fill quickly.",
        "active": True,
        "last_verified": date(2026, 5, 2),
    },
    {
        "name": "King County Mental Health Access Line",
        "category": "healthcare",
        "description": "Phone-based crisis support and referral line connecting callers to mental health and substance use treatment providers countywide.",
        "eligibility_notes": "Open to all King County residents; no insurance required.",
        "service_area": "King County (phone-based, countywide)",
        "address": "N/A - phone service",
        "phone": "206-555-0100",
        "website": "https://kcmhaccess.example.org",
        "hours": "24/7",
        "application_process": "Call the access line directly; no appointment needed.",
        "active": True,
        "last_verified": date(2026, 6, 25),
    },
    # ---- Employment ----
    {
        "name": "Northgate WorkForce Center",
        "category": "employment",
        "description": "Job training, resume assistance, and job placement services, including a computer lab for job applications.",
        "eligibility_notes": "Open to adults 18+ seeking employment; no residency requirement.",
        "service_area": "North Seattle",
        "address": "10500 5th Ave NE, Seattle, WA 98125",
        "phone": "206-555-0233",
        "website": "https://northgateworkforce.example.org",
        "hours": "Mon-Fri 9am-5pm",
        "application_process": "Drop in during business hours or schedule online.",
        "active": True,
        "last_verified": date(2026, 4, 8),
    },
    {
        "name": "SouthEnd Career Pathways",
        "category": "employment",
        "description": "Career coaching and vocational training program with a focus on healthcare and construction trade pathways.",
        "eligibility_notes": "Priority for low-income residents of South King County; must be authorized to work in the US.",
        "service_area": "Tukwila, SeaTac, Renton",
        "address": "14900 Interurban Ave S, Tukwila, WA 98168",
        "phone": "206-555-0246",
        "website": "https://southendcareerpathways.example.org",
        "hours": "Mon-Fri 8:30am-4:30pm",
        "application_process": "Attend a weekly orientation session (see website for schedule) to enroll.",
        "active": True,
        "last_verified": date(2026, 5, 19),
    },
    {
        "name": "Cascade Youth Employment Program",
        "category": "employment",
        "description": "Paid job training and internship placement program for young adults, including workplace readiness workshops.",
        "eligibility_notes": "Ages 16-24; must reside in King County.",
        "service_area": "Renton and South King County",
        "address": "1055 S Grady Way, Renton, WA 98057",
        "phone": "425-555-0177",
        "website": "https://cascadeyouthemployment.example.org",
        "hours": "Mon-Fri 10am-6pm",
        "application_process": "Online application; cohorts start quarterly.",
        "active": True,
        "last_verified": date(2026, 2, 14),
    },
    # ---- Childcare ----
    {
        "name": "Little Sprouts Childcare Subsidy Program",
        "category": "childcare",
        "description": "Helps low-income families cover the cost of licensed childcare through direct subsidy payments to participating providers.",
        "eligibility_notes": "Household income at or below 60% state median income; child must be under 13.",
        "service_area": "Seattle citywide",
        "address": "4700 Rainier Ave S, Seattle, WA 98118",
        "phone": "206-555-0261",
        "website": "https://littlesproutssubsidy.example.org",
        "hours": "Mon-Fri 9am-4pm (phone and in-person)",
        "application_process": "Complete an application packet; processing takes approximately 2-3 weeks.",
        "active": True,
        "last_verified": date(2026, 6, 8),
    },
    {
        "name": "Rainier Valley Early Learning Center",
        "category": "childcare",
        "description": "Subsidized preschool and early learning program for children ages 3-5, with a focus on school readiness.",
        "eligibility_notes": "Income-based sliding scale; some slots reserved for families experiencing homelessness.",
        "service_area": "Rainier Valley, Seattle",
        "address": "5250 Rainier Ave S, Seattle, WA 98118",
        "phone": "206-555-0274",
        "website": "https://rainiervalleyearlylearning.example.org",
        "hours": "Mon-Fri 7:30am-5:30pm",
        "application_process": "Tour required before enrollment; contact front desk to schedule.",
        "active": True,
        "last_verified": date(2026, 3, 22),
    },
    {
        "name": "Kent Family Childcare Resource Network",
        "category": "childcare",
        "description": "Referral service connecting families with licensed childcare providers, plus limited emergency childcare vouchers.",
        "eligibility_notes": "Open to all Kent-area families; emergency vouchers prioritized for households in crisis.",
        "service_area": "Kent and Covington",
        "address": "220 4th Ave S, Kent, WA 98032",
        "phone": "253-555-0188",
        "website": "https://kentchildcarenetwork.example.org",
        "hours": "Mon-Fri 9am-5pm",
        "application_process": "Call or email to request a referral packet.",
        "active": True,
        "last_verified": date(2026, 5, 30),
    },
    # ---- Financial Assistance ----
    {
        "name": "Emerald City Utility Assistance Fund",
        "category": "financial_assistance",
        "description": "One-time grants to help households cover past-due electric, gas, or water bills and avoid shutoff.",
        "eligibility_notes": "Must have a shutoff notice or past-due bill; income at or below 200% federal poverty level.",
        "service_area": "Seattle citywide",
        "address": "810 3rd Ave, Seattle, WA 98104",
        "phone": "206-555-0299",
        "website": "https://emeraldcityutilityfund.example.org",
        "hours": "Mon-Fri 9am-4pm",
        "application_process": "Submit a copy of the utility bill along with the online application.",
        "active": True,
        "last_verified": date(2026, 6, 18),
    },
    {
        "name": "King County Emergency Cash Assistance",
        "category": "financial_assistance",
        "description": "Short-term emergency cash grants for households facing an unexpected financial crisis (car repair needed for work, funeral costs, etc.).",
        "eligibility_notes": "King County residency required; one grant per household per 12 months.",
        "service_area": "King County (countywide)",
        "address": "401 5th Ave, Seattle, WA 98104",
        "phone": "206-555-0301",
        "website": "https://kingcountyemergencyfunds.example.org",
        "hours": "Mon-Fri 8am-5pm",
        "application_process": "Call the intake line to determine eligibility before applying.",
        "active": True,
        "last_verified": date(2026, 4, 26),
    },
    {
        "name": "Auburn Community Action Fund",
        "category": "financial_assistance",
        "description": "Provides small grants for rent, utilities, or essential household items to Auburn-area families in crisis.",
        "eligibility_notes": "Auburn or Algona residency required; documentation of crisis (eviction notice, shutoff notice, etc.) requested.",
        "service_area": "Auburn and Algona",
        "address": "910 8th St NE, Auburn, WA 98002",
        "phone": "253-555-0142",
        "website": "https://auburncommunityaction.example.org",
        "hours": "Tue and Thu 10am-3pm",
        "application_process": "In-person appointment required; call to schedule.",
        "active": True,
        "last_verified": date(2026, 1, 30),
    },
    {
        "name": "Federal Way Financial Navigator Program",
        "category": "financial_assistance",
        "description": "One-on-one financial coaching combined with referrals to emergency assistance programs and benefits enrollment help.",
        "eligibility_notes": "Open to all Federal Way residents; no income documentation required for the coaching service itself.",
        "service_area": "Federal Way",
        "address": "33325 8th Ave S, Federal Way, WA 98003",
        "phone": "253-555-0163",
        "website": "https://fwfinancialnavigator.example.org",
        "hours": "Mon-Fri 9am-5pm",
        "application_process": "Schedule a free coaching session online or by phone.",
        "active": True,
        "last_verified": date(2026, 5, 14),
    },
    # ---- Legal ----
    {
        "name": "Sound Legal Aid Society",
        "category": "legal",
        "description": "Free civil legal representation and advice for tenant rights, family law, and public benefits appeals.",
        "eligibility_notes": "Income at or below 125% federal poverty level for full representation; free consultations for all.",
        "service_area": "Seattle and King County",
        "address": "1200 5th Ave, Seattle, WA 98101",
        "phone": "206-555-0311",
        "website": "https://soundlegalaid.example.org",
        "hours": "Mon-Fri 9am-5pm",
        "application_process": "Call the intake line; consultations scheduled within 1-2 weeks.",
        "active": True,
        "last_verified": date(2026, 6, 22),
    },
    {
        "name": "Eastside Immigrant Legal Clinic",
        "category": "legal",
        "description": "Legal consultation and representation for immigration matters, including asylum applications and status adjustments.",
        "eligibility_notes": "Sliding-scale fees; free consultations for low-income clients.",
        "service_area": "Bellevue, Redmond, and the Eastside",
        "address": "1601 116th Ave NE, Bellevue, WA 98004",
        "phone": "425-555-0188",
        "website": "https://eastsideimmigrantlegal.example.org",
        "hours": "Mon, Wed, Fri 10am-4pm",
        "application_process": "Call to schedule an initial consultation.",
        "active": True,
        "last_verified": date(2026, 3, 5),
    },
    {
        "name": "King County Eviction Defense Project",
        "category": "legal",
        "description": "Emergency legal representation for tenants facing eviction, including same-day help for upcoming court dates.",
        "eligibility_notes": "Must have an active or pending eviction case in King County; income limits apply for full representation.",
        "service_area": "King County (countywide)",
        "address": "516 3rd Ave, Seattle, WA 98104",
        "phone": "206-555-0322",
        "website": "https://kcevictiondefense.example.org",
        "hours": "Mon-Fri 8:30am-4:30pm; emergency line available for imminent court dates",
        "application_process": "Call the emergency line immediately if you have an upcoming eviction hearing.",
        "active": True,
        "last_verified": date(2026, 6, 30),
    },
]
